#!/usr/bin/env bash
# Installs nginx on web01 server and by default it listens on port 80.
# updates contents to be displayed once request is made to the web server,
# information displayed should be "Hello World"

sudo su
apt-get -y  update
apt-get -y install nginx-core
cp /etc/nginx/modules-available/default /etc/nginx/modules-enabled/default
echo "Hello World" > /var/www/html/index.html
service nginx restart
