#!/usr/bin/env bash
# Installs nginx on web01 server and by default it listens on port 80.
# updates contents to be displayed once request is made to the web server,
# information displayed should be "Hello World"

sudo apt-get -y  update
sudo apt-get -y install nginx
echo "Hello World" > /var/www/html/index.nginx-debian.html
service nginx restart
