#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to
# another page.
# Install necessary packages e.g. nginx

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://https://www.youtube.com/watch?v=_ir9du6fq4Q/ permanent;' \
/etc/nginx/sites-available/default
sudo service nginx restart
