#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string:
# "Ceci n'est pas une page".

sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/error-doc404.html > /dev/null
sudo sed -i '46i error_page 404 / error-doc404.html;' /etc/nginx/sites-available/default
sudo service nginx restart
