#!/usr/bin/env bash
# Netstat command below executes to show listening ports:
# - That only show listening sockets
# - That shows the PID and name of the program to which each socket belongs
netstat -l -p
