#!/usr/bin/env bash
# Debuging ubuntu container's nginx  installation.
# nginx should be running and listening on port 80 of all server's active IPV4IPs.

# Navigating to sites-enabled dir for nginx
cd /etc/nginx/sites-enabled/ || exit

# Deleting the default file which contains acive
# or enabled configurations.
rm default

# Creating a symbolic link to capture any changes made
# default file in sites-available dir, which will reflect
# on default file in sites-enabled dir
ln -s /etc/nginx/sites-available/default default

# restart service
service nginx restart
