#!/usr/bin/env bash
# Configure nginx to listen on port 80
cat /etc/nginx/sites-available/default > /etc/nginx/sites-enabled/default
service nginx restart # Restart nginx service
service nginx stop # stop nginx service
