#!/usr/bin/env bash
# Configure nginx to listen on port 80
sed -i 's/8080/80' /etc/nginx/sites-enabled/default
service nginx restart # Restart nginx service
kill "$(pgrep 'ngix' | head -1)" # Terminate the 1st nginx process
