#!/usr/bin/env bash
# Defined a script which changes IP of Local host and facebook
# site on ubuntu server.
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
# Restart networking service
service networking restart
